### ISSUE TITLE
Ultrawide resolution causes compressed albums in new albums view

### ISSUE THREAD

**Issue by jacksongoode** [BeardedBear/beardify#144]
![Screen Shot 2022-06-02 at 9 36 05 AM](https://user-images.githubusercontent.com/54308792/171680833-da5637c3-b07f-4ac3-9c76-e97d16fa7162.jpg)

Might be an issue in some other panels as well?

**Comment by BeardedBear** [comment]
Haha I know about this bug, but I thought I was the only one using my custom Spotify client, so I didn't fix it, so I will! 

You're very brave to keep using it, with the bugs that Spotify's API has created by changing endpoints and lowering the speed of responses in the last weeks without warning us

**Comment by BeardedBear** [comment]
@jacksongoode it should be fixed :)

**Comment by jacksongoode** [comment]
> You're very brave to keep using it, with the bugs that Spotify's API has created by changing endpoints and lowering the speed of responses in the last weeks without warning us

That's really interesting to hear! Is there a collective response to this somewhere? Have other developers using the API noticed this?

**Comment by BeardedBear** [comment]
Yep, there is some issues in the dev forum : https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer

- For example, during like 1 week, `currently-playing` endpointAPI return always 0 on `progress_ms`, so seekbar was broken : 
    - https://community.spotify.com/t5/Spotify-for-Developers/currently-playing-returning-incorrect-progress-ms/td-p/5380840
    - https://community.spotify.com/t5/Spotify-for-Developers/Progress-not-updating-correctly-when-playing-from-the-Web/m-p/5383093

Or before the update, `/play` or `/pause` was returning correct state of the player, now he return the state before call endpoint, so i must make ugly fixes

**Comment by BeardedBear** [comment]
one day I will take the time to rework the state of playing from scratch ^^
